robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60  

  # Position Controllers ---------------------------------------
  left_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_left_joint
    pid: {p: 0.1, i: 0.01, d: 0.001}
  right_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_right_joint
    pid: {p: 0.1, i: 0.01, d: 0.001}